### ISSUE TITLE
per-instance.sh: Fix PUBIP function

### ISSUE THREAD

**Issue by merkys7** [litespeedtech/ls-cloud-image#15]
Happy easter! @Code-Egg I hope you are doing well

I would like to inquire about the potential fix for the following line:
https://github.com/litespeedtech/ls-cloud-image/blob/38430f2373f87d74f2c085e8cfa196255c06447b/Cloud-init/per-instance.sh#L143

The problem:
Command: `ip -4 route get 8.8.8.8 | awk {'print $7'} | tr -d '\n'` doesn't return anything on OpenVZ container.

The correct command on OpenVZ would be:
```
ip -4 route get 8.8.8.8 | awk {'print $5'} | tr -d '\n'
```

I suggest the solution to use universal method such as: ```curl -4 icanhazip.com``` because routes are different on every provider

What do You think?

**Comment by Code-Egg** [comment]
HIHI, 

Will do. Do you think 
`curl -s http://checkip.amazonaws.com || printf "0.0.0.0"` is more stable/reliable than icanhazip.com?

**Comment by merkys7** [comment]
I think `checkip.amazonaws.com` is more stable

**Comment by Code-Egg** [comment]
https://github.com/litespeedtech/ls-cloud-image/commit/210ff2c54b0dbe1b71d2d35713560440d8af7a68

All done

**Comment by merkys7** [comment]
Thank You very much

**Comment by Code-Egg** [comment]
Sure thing, let me know if there's any more suggestions.
