### ISSUE TITLE
Default Package on CyberPanel installation

### ISSUE THREAD

**Issue by merkys7** [litespeedtech/ls-cloud-image#16]
Considering you are just starting with the CyberPanel, there is high chance you will run into an issue after migrating the website to CyberPanel due to low Default package Disk Space and Bandwidth limit.

I highly recommend setting the following values to 0 - https://prnt.sc/s8949e

If that's not possible, perhaps you know any workaround? I believe this information is not saved as a file.

Any help is highly appreciated

**Comment by Code-Egg** [comment]
HIHI,

Right, the default value maybe not enough in some cases, but the Default package can be simply updated from **CyberPanel > Packages > List packages > Edit** with the new value you need, then click **Save** button to apply to Domains. 

If we have 0 = unlimited as default value, it maybe not ideal for hosting manager. 
Hope it helps.

**Comment by merkys7** [comment]
Thank you for this information

I am writing tutorial/article:
How to move from X panel to CyberPanel.

And the problem is that I need to write about add the required step for the user to edit the package. While we could make this step not needed (optional) by switching to 0 for Disk space and Bandwidth. (?)


Perhaps you know if it's possible to change the default value of the default Package?

**Comment by aonsyed** [comment]
Thank you for writing such tutorials, please let us know once it's complete

The information for users and packages is stored in a database, not a file. currently, there is a CLI method for adding, listing and deleting packages listed here 
https://docs.cyberpanel.net/doku.php?id=cli
CLI doesn't support editing or updating packages yet, you could add the option run 
cyberpanel createPackage --owner admin --packageName NewPackage --diskSpace 10000 --bandwidth 100000 --emailAccounts 100 --dataBases 100 --ftpAccounts 100 --allowedDomains 100

Then they can use that package for websites, meanwhile we will try to change limits in next update

**Comment by merkys7** [comment]
Thank You very much. I will share it with you when I finish it
