### ISSUE TITLE
No MySQL environment, skip!

### ISSUE THREAD

**Issue by Alnaggar94** [litespeedtech/ls-cloud-image#27]
Hello,

I'm using Oracle cloud (Ubuntu 20.04) and I have followed the instruction to build a custom WordPress image using :
`bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/wpimgsetup.sh )`

Then I used this script to add additional Virtual Hosts:
`/bin/bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/vhsetup.sh ) -d www.example.com -w`

But I get this error:
```
Vhost created success!
No MySQL environment, skip!
Setup finished!
```

I tried to change `check_process 'mysqld'` to  `check_process 'mysql'` in "vhsetup.sh" and it worked. 
I think the issue "mysqld" not running due to unknown reasons, I have tried to do that many times with Ubuntu 20, 18 and also tried to change the Mariadb version in the script to version 10.5 instead of 10.6 and it's the same issue.

**Comment by Code-Egg** [comment]
To build an image, please follow https://github.com/litespeedtech/ls-cloud-image/wiki/Build-WordPress-Image#what-if-i-want-to-use-it-directly 
You can not miss steps 3 and 4 in order to build the image. Launch a new server from the image, then you can run the vhost creation command. 

Follow https://github.com/litespeedtech/ls-cloud-image/wiki/Build-WordPress-Image#what-if-i-want-to-use-it-directly if you want to set up and use it directly (including add additional Virtual Hosts)

**Comment by Alnaggar94** [comment]
@Code-Egg - Thanks for your reply, I tried with a fresh Ubuntu 20 installation and the issue is the same, I tried the following:

```
bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/wpimgsetup.sh )
bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Cloud-init/per-instance.sh )
reboot
```

Then tried to add additional Virtual Hosts:
`/bin/bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/vhsetup.sh ) -d m6.olfast.com.com -w`

![Capture](https://user-images.githubusercontent.com/49800146/139693698-3ad60441-7056-428f-b0a0-4cccd0620e71.PNG)

**Comment by Code-Egg** [comment]
Just checked, the image setup script now is using MariaDB v10.6 and the process name is slightly different than usual. Latest commit should fix the issue, feel free to try it again, thanks 
https://github.com/litespeedtech/ls-cloud-image/commit/50c591c18aafa595706b13ebd7d1ffd1e6f9ed59

**Comment by Alnaggar94** [comment]
Thank you so much, It works fine now
