### ISSUE TITLE
Is it possible to disable the self-signed Certificate?

### ISSUE THREAD

**Issue by droplinxuser** [litespeedtech/ls-cloud-image#29]
When testing from:
https://www.ssllabs.com/ssltest/index.html

A new domain generated from this command: 
`./vhsetup.sh -d example.com -le xxx@gmail.com -f`

I got this result:
https://imgur.com/cJNcnGD

This is OLS by the way.

**Comment by droplinxuser** [comment]
And it cause this notice:
This site works only in browsers with SNI support.

**Comment by Code-Egg** [comment]
It's not a self-signed certificate, it will apply with let's encrypt. Did you apply with a valid domain? and what's the output of that command? 
SNI is a different thing, you can remove the wildcard from the listener.

**Comment by droplinxuser** [comment]
I mean this red flag issue:
https://imgur.com/cJNcnGD

**Comment by Code-Egg** [comment]
Correct, you should not get those warnings if your cert applied successfully.
