### ISSUE TITLE
Session resumption (caching) - No (IDs assigned but not accepted)

### ISSUE THREAD

**Issue by droplinxuser** [litespeedtech/ls-cloud-image#30]
When testing from:
https://www.ssllabs.com/ssltest/index.html

A new domain generated from this command:
`./vhsetup.sh -d example.com -le xxx@gmail.com -f`

I got this result:
Session resumption (caching) No (IDs assigned but not accepted)

This is OLS by the way.
Is this fixable?
On Nginx based servers I don't have this issue.

**Comment by Code-Egg** [comment]
I think this is the same question to https://github.com/litespeedtech/ls-cloud-image/issues/29, so I will close this. 
FYI, I just did a quick test, no such issue on my test domain and server.

**Comment by droplinxuser** [comment]
Can I have the SSLLabs result URL?
This is a different problem with the other ticket.

**Comment by Code-Egg** [comment]
Could you join the [golitespeed community on Slack](litespeedtech.com/slack) and message me @eric from there, so we can discuss faster.
