### ISSUE TITLE
Please add prestashop 1.7.8 On Digitalocean on openlitespeed

### ISSUE THREAD

**Issue by domaingood** [litespeedtech/ls-cloud-image#31]
Please add 
prestashop 1.7.8 On Digitalocean
OpenLiteSpeed 
Redis
Memchache
Certbot
with MySQL 8

https://github.com/PrestaShop/PrestaShop/tree/1.7.8.x

**Comment by Code-Egg** [comment]
You could take advantage of CyberPanel(https://marketplace.digitalocean.com/apps/cyberpanel) image, it has the PrestaShop app installer included.

**Comment by domaingood** [comment]
@Code-Egg Thank you for your reply. Im aware about CyberPanel. But I want to use LAMP with OpenLiteSpeed.
CyberPanel Added more services Thats Sometime we dont need.Also CyberPanel is not secure. Its better for E-commerce
use minimal services with OpenLiteSpeed on server.So Its better make One click in Digitalocean for prestashop.

**Comment by Code-Egg** [comment]
I see. Since OLS does not support ESI, to make LSCache works on PrestaShop, you may want to use LSWS. Let me know if you need more information.

**Comment by domaingood** [comment]
https://openlitespeed.org/kb/prestashop-on-openlitespeed/

**Comment by Code-Egg** [comment]
Yes, you can follow that guide. 
FYI, I just did a quick test, without cache plugin, prestashop works well with OLS.
