### ISSUE TITLE
OpenLiteSpeed ClassicPress

### ISSUE THREAD

**Issue by domaingood** [litespeedtech/ls-cloud-image#32]
https://marketplace.digitalocean.com/apps/openlitespeed-classicpress
Can you Add Redis also Add MySQL 8

Thank you

**Comment by Code-Egg** [comment]
May I know why you want MySQL 8 on all the CMS?

**Comment by domaingood** [comment]
@Code-Egg Please review https://www.percona.com/blog/2020/07/31/how-mysql-8-0-21-and-mariadb-10-5-4-perform-in-io-bound-scenarios-on-sata-ssd-and-nvme-storage/
If add percona for MYSQL 8 Its more better.

**Comment by Code-Egg** [comment]
Currently, we don't plan to rebuild image for MySQL, but I have added the --with-mysql option to [ols1clk](https://github.com/litespeedtech/ols1clk) for you, now you can use ols1clk.sh --wordpress --with-mysql on your fresh VPS.
