### ISSUE TITLE
Script to add a new virtual host for the Litespeed Enterprise version

### ISSUE THREAD

**Issue by Alnaggar94** [litespeedtech/ls-cloud-image#33]
Hello
I used this command to upgrade to Litespeed Enterprise and all the current vhosts converted to work with Litespeed Enterprise fine:
`/bin/bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/ols2ent-v2.sh )`

But I can't add a new virtual host using the script `vhsetup.sh` I tried to add a new domain after I upgraded to Litespeed Enterprise using the command:
`bash vhsetup.sh -d domain.com`
and it doesn't work. 

It will be great if there is a simple script to add a new virtual host for the Litespeed Enterprise version like the `vhsetup.sh` script in Openlitespeed

**Comment by Code-Egg** [comment]
Thanks for the suggestion, will see what we can do.

**Comment by Alnaggar94** [comment]
Thanks for your reply, I hope we can see it soon

**Comment by Code-Egg** [comment]
Done, please give it a try and let me know if there's any issue. 

And, I'd recommend you to add `--backup` parameter when adding or deleting vhost, it will back up the server config file just in case the new code goes wrong. 
```
bash vhsetup.sh -d domain.com --backup
```
