### ISSUE TITLE
OpenLiteSpeed Drupal 9

### ISSUE THREAD

**Issue by domaingood** [litespeedtech/ls-cloud-image#34]
OpenLiteSpeed Drupal 9
https://marketplace.digitalocean.com/apps/openlitespeed-wordpress
https://openlitespeed.org/kb/drupal8/

Please add drupal 9 for OpenLiteSpeed

**Comment by Code-Egg** [comment]
@domaingood 
Here you go https://marketplace.digitalocean.com/apps/openlitespeed-drupal
