### ISSUE TITLE
OpenLiteSpeed Backdrop CMS

### ISSUE THREAD

**Issue by domaingood** [litespeedtech/ls-cloud-image#35]
OpenLiteSpeed Backdrop CMS
Its a Classic Drupal 7.
https://backdropcms.org/

Please add Backdrop CMS for OpenLiteSpeed

**Comment by Code-Egg** [comment]
That's an old version, should just use the latest and official one, https://docs.litespeedtech.com/cloud/images/drupal/ 
And I don't think Drupal CLI supports that version well?

**Comment by domaingood** [comment]
I asked for OpenLiteSpeed Backdrop CMS ( https://backdropcms.org/ ). Like classicpress
https://marketplace.digitalocean.com/apps/openlitespeed-classicpress

**Comment by Code-Egg** [comment]
I know, but there are really not many people use those forked old/classic CMS actually. And it may not support the latest PHP, plugins, composer, and drush well. I'd recommend you to fork this repo and update https://github.com/litespeedtech/ls-cloud-image/blob/master/Setup/drupalsetup.sh#L507-L516 to satisfy your need.

**Comment by domaingood** [comment]
HI [Code-Egg](https://github.com/Code-Egg),
Thanks for info.But I worked closely with backdrop. and backdrop works with php 8.1 and latest module and drush as well.We are some deferent from drupal.

**Comment by domaingood** [comment]
https://forum.backdropcms.org/forum/no-thumbnails-library

**Comment by Code-Egg** [comment]
Hi, 
We don't have a plan to maintain a forked project, maybe you could build and provide it in the marketplace.
