### ISSUE TITLE
How to manually run interactive script after step 4?

### ISSUE THREAD

**Issue by Lolosan** [litespeedtech/ls-cloud-image#4]
Ubuntu 18.04

After step 4, when relogin to ssh, i'm not geting interactive script to finish setup

How can i run it manually?

**Comment by Code-Egg** [comment]
May I know which step 4 you mean? 
like after "Do you wish to force HTTPS rewrite rule for this domain? [y/N]"? 
If you already added domain and applied SSL success, then you should no need to run it again. 

FYI, script is [here](https://github.com/litespeedtech/ls-cloud-image/blob/master/Setup/domainsetup.sh)

 If you want to setup another domain and apply SSL for it, please use [vhsetup script](https://github.com/litespeedtech/ls-cloud-image/blob/master/Setup/vhsetup.sh)

**Comment by Lolosan** [comment]
Thank you for your fast reply

I meant step 4 in wiki tutorial: https://github.com/litespeedtech/ls-cloud-image/wiki

What i'm doing is:

launch new ubuntu 18.04 instance
sudo su
apt update && apt upgrade

bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/wpimgsetup.sh )

bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Cloud-init/claunch.sh ) 

Take snapshot
--
On relogin, domain and ssl setup is expected. Didn't happen

Tried bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/domainsetup.sh ) 

But ssl ends with error that it cant verify

**Comment by Code-Egg** [comment]
Hi,
I see. Generally you should see a welcome banner and interactive script. 
It's possible something failed in cloud init, or maybe there's no cloud init package from the base image. Could you check if any error shows on /var/log/cloud-init.log ?

Welcome to join [LiteSpeed Community via Slack ](https://join.slack.com/t/golitespeed/shared_invite/enQtMzE5ODgxMTUyNTgzLTNiNWQ1MWZlYmI4YjEzNTM4NjdiODY2YTQ0OWVlMzBlNGZkY2E3Y2E4MjIzNmNmZmU0ZjIyNWM1ZmNmMWRlOTk)and message me @Eric, should be able to help you faster if you like.

**Comment by umarmughal** [comment]
@Lolosan Hey did you find the way how to add domain once auto script is disabled, i am also stuck in same situation.

**Comment by Code-Egg** [comment]
@umarmughal I probably helped you on the community if I remember correctly. Will close it.
