### ISSUE TITLE
Setup/vhsetup.sh bug

### ISSUE THREAD

**Issue by QINGCHARLES** [litespeedtech/ls-cloud-image#46]
Setup/vhsetup.sh has a function called install_ed which is no longer called, and it has a call to "cked" which causes an error.

Any ideas?

**Comment by Code-Egg** [comment]
Thanks, [the latest commit](https://github.com/litespeedtech/ls-cloud-image/commit/165dc4ae7b8b51b35b9a7abd9dc96398ae964159) has it fixed.

**Comment by QINGCHARLES** [comment]
Tested and it works👍
