### ISSUE TITLE
Centos 9 crontab logic skipped

### ISSUE THREAD

**Issue by shor0814** [litespeedtech/ls-cloud-image#47]
When generating the crontab for the certbot check, the logic skips Centos 9.  I assume that the entry for one of the other versions will work correctly.

Maybe:

elif [ "${OSNAME}" = 'centos' ]; then
            if [ "${OSVER}" = '7' ]; then
                echo "0 0,12 * * * root python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew -q --deploy-hook 'systemctl restart lsws'" \
                | sudo tee -a /etc/crontab > /dev/null
            elif [ "${OSVER}" = '8' ]; then
                echo "0 0,12 * * * root python3 -c 'import random; import time; time.sleep(random.random() * 3600)' && /usr/local/bin/certbot renew -q --deploy-hook 'systemctl restart lsws'" \
                | sudo tee -a /etc/crontab > /dev/null
            **elif [ "${OSVER}" = '9' ]; then
                echo "0 0,12 * * * root python3 -c 'import random; import time; time.sleep(random.random() * 3600)' && /usr/local/bin/certbot renew -q --deploy-hook 'systemctl restart lsws'" \
                | sudo tee -a /etc/crontab > /dev/null**
            else
                echoY 'Please check certbot crontab'

Love the utilities.

**Comment by Code-Egg** [comment]
Thanks. I just updated the vhost script in [the latest commit ](https://github.com/litespeedtech/ls-cloud-image/commit/68b1fb4db8bf4e91f437f3fd3f9df695144eb3d4)
