### ISSUE TITLE
BUG: typo in OLS rails example setup

### ISSUE THREAD

**Issue by climatebrad** [litespeedtech/ls-cloud-image#49]
In https://github.com/litespeedtech/ls-cloud-image/blob/6097697cc43f8436cba93fce96a13dde3099cee6/Setup/railssetup.sh#L454

`"rails/welcome#index"` should be `"welcome#index"`, as

https://github.com/litespeedtech/ls-cloud-image/blob/6097697cc43f8436cba93fce96a13dde3099cee6/Setup/railssetup.sh#L450

generates WelcomeController, not Rails::WelcomeController.

**Comment by Code-Egg** [comment]
Thanks, just fixed it in [the latest commit](https://github.com/litespeedtech/ls-cloud-image/commit/74334ac2912e4b46dc0a6d0bb947fde1fe13df4b).
