### ISSUE TITLE
Change default lsphp version

### ISSUE THREAD

**Issue by fizikiukas** [litespeedtech/ls-cloud-image#50]
In OLS images build on Ubuntu 24.04 the default PHP version is 8.3, because LiteSpeed repo does not have PHP 7.4 - https://rpms.litespeedtech.com/debian/dists/noble/main/binary-amd64/Packages

However, vhsetup.sh script asks for lsphp74, which is no longer present in new installations.

I would suggest to change:

PHPVER=lsphp74 -> PHPVER=lsphp83

https://github.com/litespeedtech/ls-cloud-image/blob/master/Setup/vhsetup.sh#L23

**Comment by Code-Egg** [comment]
Sure, updated.
